// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CharacterAnimations","status":false,"description":"(v.1.8) Make the player and follower characters use different\r\ngraphics for idle, walk and run. View HELP for more info.","parameters":{"Use Jump Graphic":"true","Common Event ID":"0","Common Event Time":"0","Repeat Common Event":"0"}},
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.4) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}}
];
