// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CharacterAnimations","status":false,"description":"(v.1.8) Make the player and follower characters use different\r\ngraphics for idle, walk and run. View HELP for more info.","parameters":{"Use Jump Graphic":"true","Common Event ID":"0","Common Event Time":"0","Repeat Common Event":"0"}},
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.4) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}},
{"name":"Input Combo Skills","status":false,"description":"This script enables the usage of Active Chain Skills.","parameters":{"Settings":"","DefaultInputTimer":"500","DefaultActionDelayStart":"60","Inputs":"[\"{\\\"InputName\\\":\\\"pageup\\\",\\\"KeyName\\\":\\\"Q\\\"}\",\"{\\\"InputName\\\":\\\"pagedown\\\",\\\"KeyName\\\":\\\"W\\\"}\",\"{\\\"InputName\\\":\\\"a\\\",\\\"KeyName\\\":\\\"A\\\"}\",\"{\\\"InputName\\\":\\\"s\\\",\\\"KeyName\\\":\\\"S\\\"}\",\"{\\\"InputName\\\":\\\"d\\\",\\\"KeyName\\\":\\\"D\\\"}\"]"}},
{"name":"NRP_ChainSkill","status":true,"description":"v1.101 Chain skills together.","parameters":{"<PassiveCondition>":"","TargetDamageType":"1,5","TargetHitType":"0,1,2","TargetSkillType":"0,2","TargetForOneSkill":"false","DisplayNameStyle":"1","NoStartMotion":"true","NoStepBack":"true","NoMpTpCost":"true","IgnoreSkillConditions":"true","AbortTargetDeath":"false","AbortTargetResist":"false","DisableSameSkill":"true","AdjustAllRangeTarget":"top","NoEnemyFlash":"true","ImmortalState":"3"}},
{"name":"Input","status":true,"description":"","parameters":{}}
];
